drop table public.cmo_monthly_prices
;
CREATE TABLE IF NOT EXISTS public.cmo_monthly_prices
(       
        Month character varying COLLATE pg_catalog."default" NOT NULL,
	Crude_oil_average NUMERIC (10, 2),
	Crude_oil_Brent NUMERIC (10, 2),
	Crude_oil_Dubai NUMERIC (10, 2),
	Crude_oil_WTI NUMERIC (10, 2),
	Coal_Australian NUMERIC (10, 2),
	Coal_South_African NUMERIC (10, 2),
	Natural_gas_US NUMERIC (10, 2),
	Natural_gas_Europe NUMERIC (10, 2),
	Liquefied_natural_gas_Japan NUMERIC (10, 2),
	Natural_gas_index NUMERIC (10, 2),
	Cocoa NUMERIC (10, 2),
	Coffee_Arabica NUMERIC (10, 2),
	Coffee_Robusta NUMERIC (10, 2),
	Tea_avg_3_auctions NUMERIC (10, 2),
	Tea_Colombo NUMERIC (10, 2),
	Tea_Kolkata NUMERIC (10, 2),
	Tea_Mombasa NUMERIC (10, 2),
	Coconut_oil NUMERIC (10, 2),
	Groundnuts NUMERIC (10, 2),
	Fish_meal NUMERIC (10, 2),
	Groundnut_oil NUMERIC (10, 2),
	Palm_oil NUMERIC (10, 2),
	Palm_kernel_oil NUMERIC (10, 2),
	Soybeans NUMERIC (10, 2),
	Soybean_oil NUMERIC (10, 2),
	Soybean_meal NUMERIC (10, 2),
	Rapeseed_oil NUMERIC (10, 2),
	Sunflower_oil NUMERIC (10, 2),
	Barley NUMERIC (10, 2),
	Maize NUMERIC (10, 2),
	Sorghum NUMERIC (10, 2),
	Rice_Thai_5_Percent NUMERIC (10, 2),
	Rice_Thai_25_Percent NUMERIC (10, 2),
	Rice_Thai NUMERIC (10, 2),
	Rice_Vietnamese NUMERIC (10, 2),
	Wheat_US_SRW NUMERIC (10, 2),
	Wheat_US_HRW NUMERIC (10, 2),
	Banana_Europe NUMERIC (10, 2),
	Banana_US NUMERIC (10, 2),
	Orange NUMERIC (10, 2),
	Beef NUMERIC (10, 2),
	Meat_chicken NUMERIC (10, 2),
	Meat_sheep NUMERIC (10, 2),
	Shrimps_Mexican NUMERIC (10, 2),
	Sugar_EU NUMERIC (10, 2),
	Sugar_US NUMERIC (10, 2),
	Sugar_world NUMERIC (10, 2),
	Tobacco_US NUMERIC (10, 2),
	Logs_Cameroon NUMERIC (10, 2),
	Logs_Malaysian NUMERIC (10, 2),
	Sawnwood_Cameroon NUMERIC (10, 2),
	Sawnwood_Malaysian NUMERIC (10, 2),
	Plywood NUMERIC (10, 2),
	Cotton_A_Index NUMERIC (10, 2),
	Rubber_TSR20 NUMERIC (10, 2),
	Rubber_SGP_MYS NUMERIC (10, 2),
	Phosphate_rock NUMERIC (10, 2),
	DAP NUMERIC (10, 2),
	TSP NUMERIC (10, 2),
	Urea NUMERIC (10, 2),
	Potassium_chloride NUMERIC (10, 2),
	Aluminum NUMERIC (10, 2),
	Iron_ore_cfr_spot NUMERIC (10, 2),
	Copper NUMERIC (10, 2),
	Lead NUMERIC (10, 2),
	Tin NUMERIC (10, 2),
	Nickel NUMERIC (10, 2),
	Zinc NUMERIC (10, 2),
	Gold NUMERIC (10, 2),
	Platinum NUMERIC (10, 2),
	Silver NUMERIC (10, 2),
        CONSTRAINT cmo_monthly_prices__pkey PRIMARY KEY (Month)
)   
;
--
-- Import CMO-Monthly-Prices_Clean.csv file using PgAdmin import 
--
-- Verify data exists 
-- select * from cmo_monthly_prices;
